name: ssh

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Laravel
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}

          script: |
           mkdir test
